version: 2
jobs:
  build:
    docker:
    - image: circleci/node:16
    steps:
    - run:
        name: Install Dependencies
        command: npm ci
workflows:
  version: 2
  build:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# 
# jobs:
#   build:
#     docker:
#       - image: circleci/node:16  # Use the CircleCI Node.js 16 image
# 
#     steps:
#       - run:
#           name: Install Dependencies
#           command: npm ci
# 
# workflows:
#   version: 2
#   build:
#     jobs:
#       - build