version: 2.1

orbs:
  node: circleci/node@5.1.0
  php: circleci/php@1.1.0
  docker: circleci/docker@2.4.0

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - docker/install-docker-tools
      - node/install:
          node-version: '16.13'
      - run: node --version
      - php/install-php:
          version: '7.4'
      - run: php --version
      - run: git --version
      - run: npm i
      - run: npm run env:start
      - run: npm run cypress:run

workflows:
  install:
    jobs:
      - build
